eureka:
  client:
     service-url:
          defaultZone: http://localhost:8761/eureka/
         
spring:
   application:
        name: BetterReads_BookService
        
logging:
   file:
     path: /my-logs/app.log
     name: BooksLogs/log.txt